# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 0.6
  - nightly
matrix:
  allow_failures:
    - julia: nightly
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e ' Pkg.add("Documenter"); Pkg.clone(pwd()); Pkg.build("Keys"); Pkg.test("Keys"; coverage=true)'
after_success:
  - julia -e 'include(joinpath("docs", "make.jl")); cd(Pkg.dir("Keys")); Pkg.add("Coverage"); import Coverage; Coverage.Codecov.submit(process_folder())'
