language: julia
os:
  - linux
julia:
  - 0.7
  - nightly
notifications:
  email: false
after_success:
  - julia -e 'import Keys, Pkg; Pkg.add("Coverage"); import Coverage.Codecov; Keys |> pathof |> dirname |> Codecov.process_folder |> Codecov.submit'
  - julia -e 'import Keys, Pkg; Pkg.add("Documenter"); joinpath(Keys |> pathof |> dirname |> dirname, "docs", "make.jl") |> include'
